// session actions
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const PROCEED_WITHOUT_USER_LOGIN = 'PROCEED_WITHOUT_USER_LOGIN';

// ui actions
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// form actions
export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';
export const UPDATE_CHECKBOX_VAL = 'UPDATE_CHECKBOX_VAL';
export const POPULATE_EVENT_INFO = 'POPULATE_EVENT_INFO';
export const LOAD_LOCAL_IMAGE = 'LOAD_LOCAL_IMAGE';
export const CLEAR_LOCAL_IMAGE = 'CLEAR_LOCAL_IMAGE';
export const CLEAR_EVENT_IMAGE = 'CLEAR_EVENT_IMAGE';
export const CLEAR_FORM_FIELDS = 'CLEAR_FORM_FIELDS';

// listener actions
export const FIREBASE_LISTEN_REQUESTED = 'FIREBASE_LISTEN_REQUESTED';
export const FIREBASE_LISTEN_FULFILLED = 'FIREBASE_LISTEN_FULFILLED'
export const FIREBASE_LISTEN_REJECTED = 'FIREBASE_LISTEN_REJECTED';
export const FIREBASE_LISTEN_REMOVED = 'FIREBASE_LISTEN_REMOVED';
export const FIREBASE_LISTEN_CHILD_ADDED = 'FIREBASE_LISTEN_CHILD_ADDED';
export const FIREBASE_LISTEN_CHILD_REMOVED = 'FIREBASE_LISTEN_CHILD_REMOVED';
export const FIREBASE_LISTEN_CHILD_CHANGED = 'FIREBASE_LISTEN_CHILD_CHANGED';

// user actions
export const RECEIVE_USER = 'RECEIVE_USER';

// loading actions
export const RECEIVE_FEED_PAGE = 'RECEIVE_FEED_PAGE';
export const RECEIVE_DISCOVER_FEED_PAGE = 'RECEIVE_DISCOVER_FEED_PAGE';
export const BEGIN_PAGE_FETCH = 'BEGIN_PAGE_FETCH';
export const BEGIN_USER_INFO_FETCH = 'BEGIN_USER_INFO_FETCH';
export const BEGIN_EVENT_UPLOAD = 'BEGIN_EVENT_UPLOAD';
export const COMPLETE_EVENT_UPLOAD = 'COMPLETE_EVENT_UPLOAD';

// feed actions
export const FEED_UPDATED = 'FEED_UPDATED';

// search actions
export const RECEIVE_SEARCHED_USERS = 'RECEIVE_SEARCHED_USERS';
export const RECEIVE_SEARCHED_POSTS = 'RECEIVE_SEARCHED_POSTS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const UPDATE_SEARCHED_ENTITY = 'UPDATE_SEARCHED_ENTITY';
export const TOGGLE_BAR = 'TOGGLE_BAR'

// inbox actions
export const BEGIN_INBOX_FETCH = 'BEGIN_INBOX_FETCH';
export const RECEIVE_INBOX_EVENTS = 'RECEIVE_INBOX_EVENTS';
export const BEGIN_NOTIFICATION_FETCH = 'BEGIN_NOTIFICATION_FETCH';
export const RECEIVE_NOTIFICATION_PAGE = 'RECEIVE_NOTIFICATION_PAGE';
export const MARK_NOTIFICATION_AS_READ = 'MARK_NOTIFICATION_AS_READ';

// single post actions
export const BEGIN_POST_FETCH = 'BEGIN_POST_FETCH';
export const RECEIVE_POST_DATA = 'RECEIVE_POST_DATA';
