// event notification types
const INVITE_TO_EVENT = 'INVITE_TO_EVENT';
const SHARE_EVENT = 'SHARE_EVENT';
const EVENT_TIME_CHANGE = 'EVENT_TIME_CHANGE';
const EVENT_CANCELLED = 'EVENT_CANCELLED';

// general notification types
const FOLLOWED_BY_USER = 'FOLLOWED_BY_USER';
const USER_ATTENDING = 'USER_ATTENDING';
const USER_COMMENTED = 'USER_COMMENTED';
const USER_STARRED = 'USER_STARRED';

export const EVENT_NOTIFICATION_TYPES = [
	INVITE_TO_EVENT,
	SHARE_EVENT,
	EVENT_TIME_CHANGE,
	EVENT_CANCELLED
]

export const GENERAL_NOTIFICATION_TYPES = [
	FOLLOWED_BY_USER,
	USER_ATTENDING,
	USER_COMMENTED,
	USER_STARRED
]

export const ALL_NOTIFICATION_TYPES = [
	...EVENT_NOTIFICATION_TYPES,
	...GENERAL_NOTIFICATION_TYPES
]
